name: Auto Assign Author

on:
  pull_request:
    types:
      - opened
    branches:
      - "**"

jobs:
  assign-author:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Assign pull request author
        uses: technote-space/assign-author@v1
