name: Presubmit

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - "**"

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          self: merge-gatekeeper
